# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "congleetea/ubuntu14.04"
  config.vm.box_check_update = false
  config.ssh.username = "root"
  config.ssh.password = "vagrant"
  config.ssh.insert_key = true
  config.vm.define :m0 do |m0|
    m0.vm.hostname = "m0"
    m0.vm.synced_folder "./shared", "/home/vagrant/shared"
    m0.vm.network :public_network, ip: "192.168.1.200"
    m0.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--name", "m0", "--memory", "1024", "--cpus", "1"]
    end
  end

  config.vm.define :m1 do |m1|
    m1.vm.hostname = "m1"
    m1.vm.synced_folder "./shared", "/home/vagrant/shared"
    m1.vm.network :public_network, ip: "192.168.1.201"
    m1.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--name", "m1", "--memory", "1024", "--cpus", "1"]
    end
  end

  config.vm.define :m2 do |m2|
    m2.vm.hostname = "m2"
    m2.vm.synced_folder "./shared", "/home/vagrant/shared"
    m2.vm.network :public_network, ip: "192.168.1.202"
    m2.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--name", "m2", "--memory", "1024", "--cpus", "1"]
    end
  end

end
