* Martin Theme for org-page


Martin theme for [[https://github.com/kelvinh/org-page][org-page]]. The Theme
was originally developed by [[http://allison.house/martin/][Allison House]] and
adapted for org-page by me.

** Usage
delete your index.org

#+begin_src shell
git clone https://github.com/congleetea/org-page-theme-martin.git
#+end_src

edit org-page-theme-martin/templates/index.mustache and change title and
sub-title.

change org-page config

#+begin_src emacs-lisp
(setq op/theme 'org-page-theme-martin)
#+end_src

*** Source Block syntax highlighting
The Theme is configured to use the syntax highlighting from your emacs theme. To
enable this in the configuration set:

#+begin_src emacs-lisp
(setq op/highlight-render 'htmlize)
#+end_src

To disable this and use prettify.js comment out the function in =main.js= and
the includes for prettify.js in =footer.mustache=. 

Then make sure that the following is set:
                         
#+begin_src emacs-lisp
(setq op/highlight-render 'js)
#+end_src



* License

Showcase your project in style with Martin, a bold, timeless theme for GitHub
pages! Named for the punchcutter William Martin, apprentice to John Baskerville.
This work is licensed under a
[[http://creativecommons.org/licenses/by-sa/3.0/][Creative Commons
Attribution-ShareAlike 3.0 Unported License]].
